# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Quail
                                 A QGIS plugin
 This plugin is designed to get ALA data into QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-01
        copyright            : (C) 2025 by Atlas of Living Australia
        email                : amanda.buyan@csiro.au
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Quail class from file Quail.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .quail import Quail

    return Quail(iface)


def initGui(self):
    """Initialise the GUI"""
    self.pluginButton = self.add_action(
        ":/plugins/Quail/icon.png", text=self.tr("Start"), callback=self.run, parent=self.iface.mainWindow()
    )
    self.pluginButton.setObjectName("Run_plugin")
