# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AlaQgisPlugin
                                 A QGIS plugin
 This plugin is designed to get ALA data into QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-01
        copyright            : (C) 2025 by Atlas of Living Australia
        email                : amanda.buyan@csiro.au
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AlaQgisPlugin class from file AlaQgisPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .alaQgisPlugin import AlaQgisPlugin

    return AlaQgisPlugin(iface)

def initGui(self):
    """Not sure if this is correct"""
    self.pluginButton = self.add_action(
        ':/plugins/ala-qgis-plugin/icon.png',
        text=self.tr(u'Start'),
        callback=self.run,
        parent=self.iface.mainWindow())
    self.pluginButton.setObjectName('Run_plugin')
