import os
from datetime import datetime

import galah
import geopandas as gpd
import pandas as pd
from qgis.core import QgsFeature, QgsField, QgsGeometry, QgsPointXY, QgsProject, QgsVectorLayer
from qgis.gui import QgsCheckableComboBox
from qgis.PyQt import QtCore, QtWidgets, uic
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtGui import QColor, QTextCharFormat
from qgis.PyQt.QtWidgets import QCheckBox, QComboBox, QDialog, QLabel, QMessageBox, QPushButton
from qgis.utils import iface

from .vocab import (
    attributes_dict,
    latitude_dict,
    longitude_dict,
    migratoryLists,
    nonNativeLists,
    sensitiveLists,
    taxon_selections,
    threatenedLists,
)

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), "alaQgisPlugin_dialog_base.ui"))

# Set default combo box for none
COMBOBOX_NONE_LABEL = "-- None --"


class AlaQgisPluginDialog(QtWidgets.QDialog, FORM_CLASS):
    """
    /***************************************************************************
     AlaQgisPluginDialog
                                     A QGIS plugin
     This plugin is designed to get ALA data into QGIS
     Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                                 -------------------
             begin                : 2025-10-01
             git sha              : $Format:%H$
             copyright            : (C) 2025 by Atlas of Living Australia
             email                : amanda.buyan@csiro.au
     ***************************************************************************/

    /***************************************************************************
     *                                                                         *
     *   This program is free software; you can redistribute it and/or modify  *
     *   it under the terms of the GNU General Public License as published by  *
     *   the Free Software Foundation; either version 2 of the License, or     *
     *   (at your option) any later version.                                   *
     *                                                                         *
     ***************************************************************************/
    """

    def __init__(self, parent=None):
        """
        Initialise the plugin, populate known values and link buttons to functions they
        execute upon click.
        """
        super(AlaQgisPluginDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # populate predefined values
        self._populate_atlases()
        self.atlas_select()

        # self.show_info_messagebox(text=str(galah.__version__))

        # add information
        self.basisOfRecordInformationLabel.setToolTip(
            "This denotes the way the record was recorded.  These have been split into two:\n\n"
            "Observations: Human and Machine Observations\n"
            "Specimens: Fossils, Material Samples, Living and Preserved Specimens"
        )
        self.dataProfileInformationLabel.setToolTip(
            "These are data quality profiles that can help filter out data you don't want in your data download.  Go to your relevant atlas for more details."
        )
        self.doiInformationLabel.setToolTip(
            'If you tick the "Mint a DOI" box, you will get a DOI for your query in a popup box.  You can use this DOI in the text box to the right to get the same query.'
        )
        self.emailInformationLabel.setToolTip(
            "This is your email you have registered with your chosen atlas.  To get your email registered, contact the relevant atlas."
        )
        self.presAbsInformationLabel.setToolTip(
            "This is for specifying whether or not you want absence data.  The vast majority of data in atlases are presence data."
        )
        self.reasonInformationLabel.setToolTip(
            "This denotes the reason you are downloading the data, i.e. for conservation or research."
        )

        # define the actions clicking on these buttons will run
        self.checkTaxonBackbonePushButton.clicked.connect(self.check_ala_backbone)
        self.checkNumOccurrences.clicked.connect(self.check_num_occurrences)
        self.occDownload.clicked.connect(self.download_occurrences)
        self.speciesListCountsStatuses.clicked.connect(self.get_species_list_counts_statuses)
        self.uploadSpeciesListPushButton.clicked.connect(self.upload_species_list)
        self.updateLayersPushButton.clicked.connect(self.display_layers_from_UI)
        self.atlasesComboBox.currentIndexChanged.connect(self.atlas_select)

        # create format for weekend colours
        format = QTextCharFormat()
        format.setForeground(QColor("#89CFF0"))  # purple

        # set weekends to colour other than red
        self.startDateCalendarWidget.setWeekdayTextFormat(Qt.DayOfWeek.Saturday, format)
        self.startDateCalendarWidget.setWeekdayTextFormat(Qt.DayOfWeek.Sunday, format)
        self.endDateCalendarWidget.setWeekdayTextFormat(Qt.DayOfWeek.Saturday, format)
        self.endDateCalendarWidget.setWeekdayTextFormat(Qt.DayOfWeek.Sunday, format)

    """
    /***************************************************************************
     Variable Declaration
     ***************************************************************************/

    /***************************************************************************
     * Predefined values for the plugin                                        *
     *                                                                         *
     * Dynamic Dictionaries (values from galah-python):                        *
     *                                                                         *
     *   atlasNames                                                            *
     *       List of all atlases available in galah-python                     *
     *                                                                         *
     * Initialised Plugin-Global Dictionaries:                                 *
     *                                                                         *
     *   spatialColumns                                                        *
     *       For each spatial layer in QGIS, list all column names available   *
     *       in the shape file                                                 *
     *   taxonomicColumns                                                      *
     *       For a CSV file uploaded containing taxonomic information, list    *
     *       all columns available in the file                                 *
     *                                                                         *
     ***************************************************************************/
    """

    """
    /*****************
     Combo box values
     *****************/
    """
    # get all atlases available
    atlases = galah.show_all(atlases=True)

    # initialise atlas names dict
    atlasNames = {}

    # populate the atlas names
    for i, row in atlases.iterrows():
        if row["atlas"] == "Global":
            atlasNames["GBIF"] = row["atlas"]
        elif row["atlas"] == "Kew":
            atlasNames["Kew Gardens Data Portal"] = row["atlas"]
        else:
            atlasNames[row["atlas"]] = row["atlas"]

    # add columns for getting and displaying data
    dataProfiles = {}
    reasons = {}
    spatialColumns = {}
    taxonomicColumns = {}
    speciesListLayers = None

    """
    /***************************************************************************
     Populating predefined values
     ***************************************************************************/

    /***************************************************************************
     * all of these functions will populate predefined values, which are       *
     * defined above.                                                          *
     *                                                                         *
     *   atlas_select:                                                         *
     *       change the values of reasons and data profiles depending on the   *
     *       atlas the user has selected                                       *
     *   _populate_atlases:                                                    *
     *       set default combo box values from variable `atlases`.             *
     *   _populate_data_profiles:                                              *
     *       set default combo box values from variable `dataProfiles`         *
     *   _populate_reasons:                                                    *
     *       set default combo box values from variable `reasons`              *
     *                                                                         *
     ***************************************************************************/
    """

    def atlas_select(self):
        galah.galah_config(atlas=self.atlasNames[self.atlasesComboBox.currentText()])  # , qgis=True
        self._populate_data_profiles()
        self._populate_reasons()

    def _populate_atlases(self):
        vals = list(self.atlasNames.keys())
        self.atlasesComboBox.addItems(sorted(vals))

    def _populate_data_profiles(self):

        # initialise data profiles dict
        dataProfiles = {
            COMBOBOX_NONE_LABEL: None,
        }

        # clear values
        self.dataProfileComboBox.clear()

        # get data profiles
        try:
            profiles = galah.show_all(profiles=True)
        except ValueError as e:
            self.dataProfileComboBox.addItems(sorted(list(dataProfiles.keys())))
            return None

        # add data profile values to dict
        for i, row in profiles.iterrows():
            dataProfiles[row["name"]] = row["shortName"]

        self.dataProfiles = dataProfiles

        # assign values to combo box
        self.dataProfileComboBox.addItems(sorted(list(dataProfiles.keys())))

    def _populate_reasons(self):

        # initialise reasons dict
        reasons = {
            COMBOBOX_NONE_LABEL: None,
        }

        # clear values
        self.reasonsComboBox.clear()

        # get reasons in ALA
        try:
            rs = galah.show_all(reasons=True)
        except ValueError as e:
            self.reasonsComboBox.addItems(sorted(list(reasons.keys())))
            return None

        # add reasons to dict
        for i, row in rs.iterrows():
            reasons[row["name"]] = row["id"]

        self.reasons = reasons

        # assign values to combo box
        self.reasonsComboBox.addItems(sorted(list(reasons.keys())))

    """
    /***************************************************************************
     Showing information to the user
     ***************************************************************************/

    /***************************************************************************
     * all of these functions will show information to the user, be it         *
     * information, warning or display a data table.                           *
     *                                                                         *
     *   close_dialogBox:                                                      *
     *       close a dialogBox object; also assign a specific dictionary if    *
     *       the user has closed the box without assigning columns             *
     *   get_spatial_selections_dialogBox:                                     *
     *       gets the selected columns from each shapefile combo box - these   *
     *       will be used to name the different shapes the users can choose    *
     *   get_taxon_column_names:                                               *
     *       gets the selected columns from each taxonomic combo box - these   *
     *       will be used to query galah-python                                *
     *   show_info_messagebox:                                                 *
     *       gives the user information, for example the number of records     *
     *       they will download with their current query                       *
     *   show_warning_messagebox:                                              *
     *       gives the user a warning, for example if they are missing their   *
     *       email address                                                     *
     *   show_table_dialogbox:                                                 *
     *       shows the user a table of their data, such as the taxonomy they   *
     *       will be using to query their chosen atlas                         *
     *   show_spatial_dialogbox:                                               *
     *       shows the user a table of their data, such as the taxonomy they   *
     *       will be using to query their chosen atlas                         *
     *                                                                         *
     ***************************************************************************/
    """

    def close_spatial_dialogBox(self, dialogBox=None, dialogue=None):

        # return a specific dictionary if the user has closed the window without selecting
        # anything; close the application
        if dialogue == "Closed":
            self.spatialColumns = {dialogue: dialogue}
        dialogBox.close()


    def close_species_list_dialogBox(self, dialogBox=None, dialogue=None):

        # return a specific dictionary if the user has closed the window without selecting
        # anything; close the application
        if dialogue == "Closed":
            self.speciesListLayers = None
        dialogBox.close()


    def copy_to_clipboard(self, doi=None):

        # copy text to the global clipboard on computer
        cb = QtWidgets.QApplication.clipboard()
        cb.clear(mode=cb.Clipboard)
        cb.setText(doi, mode=cb.Clipboard)


    def get_spatial_selections_dialogBox(self, dialogBox=None):

        # separate the combo boxes and labels
        comboboxes = [x for x in dialogBox.children() if type(x) is QComboBox]
        labels = [x for x in dialogBox.children() if type(x) is QLabel]

        # initialise empty dictionary for storing information
        columns = {}

        # go through all the comboboxes to see which ones the user selected
        for i, (lb, cb) in enumerate(zip(labels, comboboxes)):
            if cb.currentText() != COMBOBOX_NONE_LABEL:
                columns[lb.objectName()] = cb.currentText()

        # check whether or not we are looking for taxonomic columns or spatial columns - assign
        # dictionary to correct object
        self.spatialColumns = columns

        # close the dialog box
        self.close_spatial_dialogBox(dialogBox=dialogBox, dialogue="got selections")


    def get_data_layers_for_species_list(self, dialogBox=None):

        # get checkboxes from dialog box and intialise layers
        checkboxes = [x for x in dialogBox.children() if type(x) is QCheckBox]
        layers = []

        # see if users have checked a particular box; if so, add it to the list
        for i,cb in enumerate(checkboxes):
            if cb.clicked:
                layers.append(cb.objectName())

        # if layers have been added to the layers list, set the speciesListLayers variable 
        # to the layers list
        if len(layers) > 0:
            self.speciesListLayers = layers

        # now, close the dialog box
        self.close_species_list_dialogBox(dialogBox=dialogBox, dialogue="got selections")


    def get_taxon_column_names(self):

        # get all taxonomy comboboxes and labels for iteration
        comboboxes = [x for x in self.Taxonomy.children() if type(x) is QComboBox]
        labels = [x for x in self.Taxonomy.children() if type(x) is QLabel and x.objectName() != "speciesLabel"]

        # initialise empty dictionary for storing information
        columns = {}

        # go through all the comboboxes to see which ones the user selected
        for i, (lb, cb) in enumerate(zip(labels, comboboxes)):
            if cb.currentText() != COMBOBOX_NONE_LABEL:
                columns[cb.currentText()] = lb.objectName()

        # check whether or not we are looking for taxonomic columns or spatial columns - assign
        # dictionary to correct object
        self.taxonomicColumns = columns

    def show_doi_messagebox(self, doi=None, title=None):

        # initiate message box
        msg = QMessageBox()

        # set information and buttons in the message box
        # msg.setIcon(QMessageBox.Icon.Information)
        msg.setText(f"This is your DOI:\t\t\t\t\t\t\t\t\t\t")
        msg.setWindowTitle(title)
        msg.setStandardButtons(QMessageBox.StandardButton.Ok | QMessageBox.StandardButton.Cancel)

        # label with DOI
        label = QLabel(doi, msg)
        label.setObjectName(doi)
        label.move(40, 25)  # +2 to offset?
        label.resize(250, 50)

        # button
        msg.setButton = QPushButton("Copy DOI", msg)
        msg.setButton.move(310, 35)
        msg.setButton.clicked.connect(lambda: self.copy_to_clipboard(doi=doi))

        # show message box
        retval = msg.exec()

    def show_info_messagebox(self, text=None, title=None):

        # initiate message box
        msg = QMessageBox()

        # set information and buttons in the message box
        msg.setIcon(QMessageBox.Icon.Information)
        msg.setText(text)
        msg.setWindowTitle(title)
        msg.setStandardButtons(QMessageBox.StandardButton.Ok | QMessageBox.StandardButton.Cancel)

        # show message box
        retval = msg.exec()

    def show_spatial_dialogbox(self, title=None, selection_dict=None):

        # set offset here to do spacing maths
        offset = 30

        # set up the dialog box
        msg = QDialog()
        msg.resize(300, offset * (len(selection_dict.keys()) + 3))
        msg.setWindowTitle(title)

        # loop over keys in selection dictionary
        for i, key in enumerate(selection_dict.keys()):

            # create label
            label = QLabel(key, msg)
            label.setObjectName(key)
            label.move(offset, i * offset + offset + 5)  # +2 to offset?

            # create a combo box
            comboBox = QComboBox(msg)
            comboBox.setObjectName("{}ComboBox".format(key))
            comboBox.move(100 + offset, i * offset + offset)
            comboBox.addItems(sorted(selection_dict[key]))

        # create the Set Columns button and Cancel buttons, move them into the correct place, and link them to the
        # relevant functions
        msg.cancelButton = QPushButton("Cancel", msg)
        msg.cancelButton.move(50, int(offset * (float(len(selection_dict.keys())) + 1.5)))
        msg.cancelButton.clicked.connect(lambda: self.close_spatial_dialogBox(dialogBox=msg, dialogue="Closed"))
        msg.setButton = QPushButton("Set Columns", msg)
        msg.setButton.move(150, int(offset * (float(len(selection_dict.keys())) + 1.5)))
        msg.setButton.clicked.connect(lambda: self.get_spatial_selections_dialogBox(dialogBox=msg))

        # execute the window
        retval = msg.exec()

    def show_layers_for_species_list(self):

        # get layers from UI
        layers = self.get_layer_info_from_UI()

        # set offset here to do spacing maths
        offset = 40

        # set up the dialog box
        msg = QDialog()
        msg.resize(350, offset * (len(layers) + 3))
        msg.setWindowTitle("Select data layer(s)")

        # set up a label to inform users they can choose multiple data layers
        label = QLabel("Select data layer(s) to compile into a species list:", msg)
        label.setObjectName("message")
        label.move(10, 0)  # +2 to offset?
        label.resize(300, 50)

        # create a check box for every layer
        for i, l in enumerate(layers):

            checkBox = QCheckBox(l, msg)
            checkBox.setObjectName(l)
            checkBox.move(20 + offset, i * offset + offset)

        # create the Set Columns button and Cancel buttons, move them into the correct place, and link them to the
        # relevant functions
        msg.cancelButton = QPushButton("Cancel", msg)
        msg.cancelButton.move(50, int(offset * (float(len(layers)) + 1.5)))
        msg.cancelButton.clicked.connect(lambda: self.close_species_list_dialogBox(dialogBox=msg, dialogue="Closed"))
        msg.setButton = QPushButton("Generate List", msg)
        msg.setButton.move(150, int(offset * (float(len(layers)) + 1.5)))
        msg.setButton.clicked.connect(lambda: self.get_data_layers_for_species_list(dialogBox=msg))
        
        retval = msg.exec()

    def show_table_dialogbox(self, table=None, title=None):

        # create the window and set the title
        msg = QDialog()
        msg.setWindowTitle(title)

        # initialise the table widget
        msg.tableWidget = QtWidgets.QTableWidget(msg)

        # set scroll bars off so the table will autofill; maybe remove this
        msg.tableWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        msg.tableWidget.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)

        # get the number of rows and columns
        nb_row = table.shape[0]
        nb_col = table.shape[1]

        # set the number of rows and columns
        msg.tableWidget.setRowCount(nb_row)
        msg.tableWidget.setColumnCount(nb_col)

        # add the data to the table
        for row in range(nb_row):
            for col in range(nb_col):
                item = QtWidgets.QTableWidgetItem(str(table.iloc[row, col]))
                msg.tableWidget.setItem(row, col, item)

        # add column names
        msg.tableWidget.setHorizontalHeaderLabels(["{}".format(x) for x in table.columns])

        # resize table so user can see the table
        msg.tableWidget.resizeRowsToContents()
        msg.tableWidget.resizeColumnsToContents()

        # resize the dialog box to accommodate the table
        dialogWidth = msg.tableWidget.horizontalHeader().length() + 24
        dialogHeight = msg.tableWidget.verticalHeader().length() + 24
        msg.tableWidget.setFixedSize(dialogWidth, dialogHeight)

        # show the window
        retval = msg.exec()

    def show_warning_messagebox(self, title=None, text=None):

        # initiate message box
        msg = QMessageBox()

        # set information and buttons in the message box
        msg.setIcon(QMessageBox.Icon.Warning)
        msg.setText(text)
        msg.setWindowTitle(title)
        msg.setStandardButtons(QMessageBox.StandardButton.Ok | QMessageBox.StandardButton.Cancel)

        # show message box
        retval = msg.exec()

    """
    /***************************************************************************
     Functions for getting data from the UI
     ***************************************************************************/

    /***************************************************************************
     * all of these functions will parse input data from the UI.               *
     *                                                                         *
     *   mint_doi:                                                             *
     *       get a DOI for your query so you can easily retrieve it            *
     *   parse_authoritative_lists:                                            *
     *       get IDs of all authoritative lists user has chosen                *
     *   parse_basis_of_record:                                                *
     *       user chooses between observations and specimens; assign Darwin    *
     *       Core terms accordingly.                                           *
     *   parse_data_profile:                                                   *
     *       get variable user has chosen in data profile combo box            *
     *   parse_date:                                                           *
     *       get start date and end date values from the date tab              *
     *   parse_doi_as_query:                                                   *
     *       if someone has provided a DOI, use it as your query argument      *
     *   parse_email:                                                          *
     *       gets user email for adding to query                               *
     *   parse_filters:                                                        *
     *       parse the filters from the UI and format them for galah-python    *
     *   parse_present_absent:                                                 *
     *       determine if users want absence, presence, or both                *
     *   parse_reason:                                                         *
     *       get variable user has chosen in data profile combo box            *
     *   parse_spatial:                                                        *
     *       parse all selected spatial layers and return them to galah-python *
     *       *still need to determine if drawing bounding box                  *
     *   parse_taxonomy:                                                       *
     *       parses taxonomic names from either a text box or uploaded csv     *
     *   set_data_fields:                                                      *
     *       tells galah-python what fields to download from Python.  Checks   *
     *       whether or not user has an authoritative list in their filters    *
     *       and add statuses if so.                                           *
     *                                                                         *
     ***************************************************************************/
    """

    # check completed
    def mint_doi(self):
        if self.createDoiCheckBox.isChecked():
            return True

    # check completed
    def parse_authoritative_lists(self):

        # initialise lists variable
        lists = []

        # Threatened Lists
        if self.actThreatCheckBox.isChecked():
            lists.append(threatenedLists["ACT"])
        if self.epbcThreatCheckBox.isChecked():
            lists.append(threatenedLists["EPBC"])
        if self.nswThreatCheckBox.isChecked():
            lists.append(threatenedLists["NSW"])
        if self.ntThreatCheckBox.isChecked():
            lists.append(threatenedLists["NT"])
        if self.qldThreatCheckBox.isChecked():
            lists.append(threatenedLists["QLD"])
        if self.saThreatCheckBox.isChecked():
            lists.append(threatenedLists["SA"])
        if self.tasThreatCheckBox.isChecked():
            lists.append(threatenedLists["TAS"])
        if self.vicThreatCheckBox.isChecked():
            lists.append(threatenedLists["VIC"])
        if self.waThreatCheckBox.isChecked():
            lists.append(threatenedLists["WA"])

        # Sensitive Lists
        if self.actSensCheckBox.isChecked():
            lists.append(sensitiveLists["ACT"])
        if self.nswSensCheckBox.isChecked():
            lists.append(sensitiveLists["NSW"])
        if self.ntSensCheckBox.isChecked():
            lists.append(sensitiveLists["NT"])
        if self.qldSensCheckBox.isChecked():
            lists.append(sensitiveLists["QLD"])
        if self.saSensCheckBox.isChecked():
            lists.append(sensitiveLists["SA"])
        if self.tasSensCheckBox.isChecked():
            lists.append(sensitiveLists["TAS"])
        if self.vicSensCheckBox.isChecked():
            lists.append(sensitiveLists["VIC"])
        if self.waSensCheckBox.isChecked():
            lists.append(sensitiveLists["WA"])

        # Migratory Lists
        if self.bonnMigratoryCheckBox.isChecked():
            lists.append(migratoryLists["Bonn"])
        if self.cambaCheckBox.isChecked():
            lists.append(migratoryLists["CAMBA"])
        if self.jambaCheckBox.isChecked():
            lists.append(migratoryLists["JAMBA"])
        if self.rokambaCheckBox.isChecked():
            lists.append(migratoryLists["ROKAMBA"])

        # Non-Native Lists
        if self.nonNativeCheckBox.isChecked():
            lists.append(nonNativeLists["NonNative All"])

        # create appropriate filters for this and return as string
        if len(lists) > 0:
            return "species_list_uid={}".format(",".join(lists))
        else:
            return None

    # check completed
    def parse_basis_of_record(self):

        # declare observations vs. specimens values
        basisOfRecord_observation = [
            "HUMAN_OBSERVATION",
            "MACHINE_OBSERVATION",
            "OBSERVATION",
            "OCCURRENCE",
        ]
        basisOfRecord_specimen = [
            "FOSSIL_SPECIMEN",
            "MATERIAL_CITATION",
            "MATERIAL_SAMPLE",
            "LIVING_SPECIMEN",
            "PRESERVED_SPECIMEN",
        ]

        # declare list of potential values
        bor = []

        # check to see if any/all boxes are check
        if self.specimensCheckBox.isChecked():
            bor += basisOfRecord_specimen
        if self.observationsCheckBox.isChecked():
            bor += basisOfRecord_observation

        # create appropriate filters for this and return as string
        if len(bor) > 0:
            return "basisOfRecord={}".format(",".join(bor))
        else:
            return None

    # check completed
    def parse_data_profile(self):
        for p in self.dataProfiles:
            if self.dataProfileComboBox.currentText() == p:
                return self.dataProfiles[p]

    # check completed
    def parse_date(self):

        # get the dates and convert them to datetime
        startDate = self.startDateCalendarWidget.selectedDate()
        endDate = self.endDateCalendarWidget.selectedDate()
        d, m, y = startDate.getDate()

        # first, check for default values
        if startDate == endDate:
            if startDate == datetime.now().date():
                return None, None
            d, m, y = startDate.getDate()
            return "eventDate={}".format(datetime(d, m, y).isoformat()), None

        # then, check if someone either swapped the dates or put the wrong ones in
        elif startDate > endDate:
            self.show_warning_messagebox(text="Your start date is further in the future than your end date.")

        # otherwise, we have a valid datetime window
        else:
            if endDate == datetime.now().date():
                d, m, y = startDate.getDate()
                return "eventDate>={}Z".format(datetime(d, m, y).isoformat()), None
            else:
                d1, m1, y1 = startDate.getDate()
                d2, m2, y2 = endDate.getDate()
                startDateString = "eventDate>={}Z".format(datetime(d1, m1, y1).isoformat())
                endDateString = "eventDate=<{}Z".format(datetime(d2, m2, y2).isoformat())
                return startDateString, endDateString

        # return None as the default
        return None, None

    # check completed
    def parse_doi_as_query(self):
        doi = self.doiLineEdit.text()
        if doi not in [None, ""]:
            return doi
        return None

    # check completed
    def parse_email(self):
        return self.emailLineEdit.text()

    # check completed
    def parse_filters(self):

        # initialise filters list
        filters = []

        # get all types of filters from the UI
        authoritative_lists = self.parse_authoritative_lists()
        date1, date2 = self.parse_date()
        bor = self.parse_basis_of_record()
        pa = self.parse_present_absent()

        # loop over all filters to see which ones are present
        for fs in [authoritative_lists, bor, pa, date1, date2]:
            if fs is not None:
                filters.append(fs)

        # if there are no filters, return None
        if len(filters) == 0:
            return None

        # return whatever filters were present in the UI
        return filters

    # check completed
    def parse_present_absent(self):

        # initialise status list
        status = []

        # check if present/absent boxes are ticked
        if self.absentCheckBox.isChecked():
            status.append("ABSENT")
        if self.presentCheckBox.isChecked():
            status.append("PRESENT")

        # create appropriate filters for this and return as string
        if len(status) > 0:
            return "occurrenceStatus={}".format(",".join(status))
        else:
            return None

    # check completed
    def parse_reason(self):
        for r in self.reasons:
            if self.reasonsComboBox.currentText() == r:
                return self.reasons[r]

    def parse_spatial(self):

        # initialise geometry list
        geom_list = []

        # get the available layers
        layers = iface.mapCanvas().layers()

        # remove OpenStreetMap from the list of layers
        new_layers = [l for l in layers if l.name() != "OpenStreetMap"]

        # get all of the checkable combo boxes available
        spatial_children = [x for x in self.Spatial.children() if isinstance(x, QgsCheckableComboBox)]  # .objectName()

        # check if there are no spatial objects; if none, return None
        if len(spatial_children) == 0:
            return None
        elif len(spatial_children) > 10:
            self.show_warning_messagebox(
                text="You cannot select more than 10 shapes in your query.  You currently have {} shapes".format(
                    len(spatial_children)
                )
            )
            return "Invalid number of shapes"

        # go through all layers and only get geometries of selected
        for i, (sc, nl) in enumerate(zip(spatial_children, new_layers)):  #
            attribute = self.spatialColumns[nl.name()[0:12]]
            selected_shapes = sc.checkedItems()
            if len(selected_shapes) > 1 and "None selected" in selected_shapes:
                selected_shapes.remove("None selected")
            features = list(nl.getFeatures())
            selected_features = [f for f in features if f.attributeMap()[attribute] in selected_shapes]
            geometries = [f.geometry() for f in selected_features]
            geom_list += geometries

        # return the list of all geometries for querying
        return geom_list

    # check completed
    def parse_taxonomy(self):
        
        # initialise dictionary to make sure we cover all possible taxonomy cases
        taxonomy_dict = {
            "taxa": None,
            "identifiers": None,
            "specific_epithet": None,
            "scientific_name": None,
        }

        # check for species one might manually put in
        if self.speciesLineEdit.text() not in [None, ""]:
            taxonomy_dict["taxa"] = self.speciesLineEdit.text().split(";")  # was ,

        # make this an elif for now
        elif hasattr(self, "speciesFileLineEdit"):

            # get all objects on the Taxonomy tab
            taxon_children = [x.objectName() for x in self.Taxonomy.children()]

            # check to see if this is not None and the columns have been chosen
            if self.speciesFileLineEdit.text() not in [None, ""] and "kingdom" in taxon_children:

                # get the file name and read in the data
                file_name = self.speciesFileLineEdit.text()
                if "csv" in file_name:
                    data = pd.read_csv(file_name)
                else:
                    self.show_warning_messagebox("This file needs to be a csv.")

                # get taxonomic columns from UI
                self.get_taxon_column_names()

                # check if taxonomic columns were set - if they were, return selected taxonomic data;
                # else, return a value to let the plugin know to end functions
                if self.taxonomicColumns:

                    # if "Closed" isn't in the column names, need to get actual column names
                    if "Closed" not in self.taxonomicColumns.keys():

                        # rename the columns in the data to the Darwin Core names we need for querying
                        data_rename = data.rename(columns=self.taxonomicColumns)

                        # check to see which columns have been renamed
                        columns_in_data_rename = list(set(data_rename.columns).intersection(set(taxon_selections)))

                        # get information from the data as a dictionary of lists
                        taxon_info = data_rename[columns_in_data_rename].to_dict(orient="list")

                        # decide whether or not user should use the identifiers, specific_epithet, scientific_name
                        # or taxa argument of search_taxa
                        if "identifiers" in taxon_info.keys() and len(taxon_info.keys()) == 1:
                            taxonomy_dict["identifiers"] = taxon_info["identifiers"]
                        elif "specificEpithet" in taxon_info.keys():
                            taxonomy_dict["specificEpithet"] = taxon_info
                        elif "scientificName" in taxon_info.keys() and len(taxon_info.keys()) > 1:
                            taxonomy_dict["scientific_name"] = taxon_info
                        else:
                            taxonomy_dict["taxa"] = taxon_info["scientificName"]

                        # return dictionary
                        return taxonomy_dict

                    # return "Closed" if this appears in the dictionary, as the user has closed the previous window
                    return "Closed"

                else:

                    # assume user has not chosen any columns
                    self.show_warning_messagebox(text="Please select columns for your taxonomic arguments.")
                    return "No columns"

        # return the taxonomic dictionary
        return taxonomy_dict

    # check completed
    def set_data_fields(self):

        # set the basic data fields
        return ["basic", "dataProviderName", "stateConservation", "countryConservation"]

    """
    /***************************************************************************
     Spatial Filters
     ***************************************************************************/

    /***************************************************************************
     * all of these functions will get spatial information from the UI.        *
     *                                                                         *
     *   display_layers_from_UI:                                               *
     *       displays all layers currently in the UI, and have all fields user *
     *       can check in a searchable combo box                               *
     *   get_layer_info_from_UI:                                               *
     *       get all available layers from the UI and return a dictionary with *
     *       layers as the keys, and all possible fields for each layer as the *
     *       values                                                            *
     *                                                                         *
     ***************************************************************************/
    """

    def display_layers_from_UI(self):

        # gets layers available from UI
        layers_from_UI = self.get_layer_info_from_UI()

        # get which data column we will use for naming
        self.show_spatial_dialogbox(selection_dict=layers_from_UI)

        # set offset
        offset = 275

        # get extant combo boxes
        extant_ccb = [x for x in self.Spatial.children() if isinstance(x, QgsCheckableComboBox)]
        if len(extant_ccb) > 0:
            for ccb in extant_ccb:
                ccb.deleteLater()

        # now, get all possible shapes to select from
        if self.spatialColumns:

            # get layers
            layers = iface.mapCanvas().layers()

            # loop over layers
            for i, l in enumerate(layers):

                if any(x in l.name() for x in self.spatialColumns.keys()):

                    # get features and initialise lists
                    feature_list = []
                    features = list(l.getFeatures())

                    # get names of all features
                    for f in features:
                        feature_list.append("{}".format(f.attributeMap()[self.spatialColumns[l.name()[:12]]]))

                    # create label name for the layer
                    label = QLabel(l.name()[:12], self.Spatial)
                    label.setObjectName(l.name()[:12])
                    label.move(20 + i * offset, 80)
                    label.show()

                    # create a combo box for the layer
                    checkComboBox = QgsCheckableComboBox(self.Spatial)
                    checkComboBox.setObjectName("{}CheckComboBox".format(l.name()[:12]))  # change this
                    checkComboBox.move(20 + i * offset, 100)
                    checkComboBox.addItem("None selected")
                    checkComboBox.setItemCheckState(index=0, state=Qt.CheckState.Checked)
                    checkComboBox.addItems(["Select All"] + sorted(feature_list))
                    checkComboBox.show()


    def get_layer_info_from_UI(self):

        # get layers on the canvas
        layers = iface.mapCanvas().layers()

        # initialise dictionary of layers and potential column values
        layer_attr = {}

        # loop over all layers
        for l in layers:
            if l.name() != "OpenStreetMap":
                temp_list = [x.name() for x in list(l.fields())]
                layer_attr[l.name()[:12]] = temp_list

        return layer_attr

    def draw_bounding_box(self, shapes=None):

        # catch the case where the shapes variable is None
        if shapes is None:
            return None

        # initialise list of shapes to return
        bboxes_to_return = []

        # loop over all shapes to get bounding boxes
        for s in shapes:
            temp = s.as_shapely()
            xmin, ymin, xmax, ymax = temp.bounds
            bbox = {"xmin": xmin, "ymin": ymin, "xmax": xmax, "ymax": ymax}
            bboxes_to_return.append(bbox)

        # return bboxes
        return bboxes_to_return

    """
    /***************************************************************************
     Button actions (not galah-python functions)
     ***************************************************************************/

    /***************************************************************************
     * all of these functions will get input data from the UI.                 *
     *                                                                         *
     *   upload_species_list:                                                  *
     *       Uploads a species list from the users' computer to the UI.        *
     *   download_species_list:                                                *
     *       Downloads a species list from atlas_species() to a file.          *
     *                                                                         *
     ***************************************************************************/
    """

    def upload_species_list(self):

        # initialise the dialog
        dialog = QtWidgets.QFileDialog()
        dialog.setFileMode(QtWidgets.QFileDialog.FileMode.ExistingFiles)

        # if user chooses this option, look through the files and
        if dialog.exec():

            # get the selected file name
            file_name = dialog.selectedFiles()

            # check if user is loading csv file - if it isn't CSV, then throw error
            if file_name[0].endswith(".csv"):
                _translate = QtCore.QCoreApplication.translate
                self.speciesFileLineEdit = QtWidgets.QLineEdit(self.Taxonomy)
                self.speciesFileLineEdit.setGeometry(QtCore.QRect(490, 85, 241, 21))  # was 160, 135
                self.speciesFileLineEdit.setObjectName("speciesFileLineEdit")
                self.speciesFileLineEdit.setText(_translate("AlaQgisPluginDialogBase", file_name[0]))
                self.speciesFileLineEdit.show()
            else:
                self.show_info_messagebox("Please provide a CSV file.")

        # display values that will be used for taxonomic columns on the UI
        self.show_taxonomic_columns()

    def download_species_list(self, species_list=None):

        # get the file name
        name, _ = QtWidgets.QFileDialog.getSaveFileName(self, "Save File")

        # check for allowed extensions; throw error if extension not correct
        if "csv" in name:
            species_list.to_csv(name, index=False)
        elif any(x in name for x in ["xls", "xlsx"]):
            species_list.to_excel(name)
        else:
            self.show_warning_messagebox(text="You can only save a CSV or an Excel spreadsheet.")

    def show_taxonomic_columns(self):

        # check if a user has uploaded a file yet
        if hasattr(self, "speciesFileLineEdit"):

            # check to see if this is not None
            if self.speciesFileLineEdit.text() not in [None, ""]:

                # get the file name and read in the data
                file_name = self.speciesFileLineEdit.text()
                if "csv" in file_name:
                    data = pd.read_csv(file_name)
                else:
                    self.show_warning_messagebox("This file needs to be a csv.")

                # create the selections dictionary to pass to the show selections dialog,
                # including a default of None
                selection_dict = {x: [COMBOBOX_NONE_LABEL] + list(data.columns) for x in taxon_selections}

                # check if taxonomic columns were set - if they were, return selected taxonomic data;
                offset1 = 250
                offset2 = 30
                i_offset = 0
                j = 0

                # if "Closed" isn't in the column names, need to get actual column names
                for i, key in enumerate(taxon_selections):

                    # add them to the UI
                    # create label name for the layer
                    label = QLabel(key, self.Taxonomy)
                    label.setObjectName(key)
                    label.move(20 + (i - i_offset) * offset1, 180 + j * offset2)
                    label.show()  # +2 to offset?

                    # create a combo box for the layer
                    comboBox = QComboBox(self.Taxonomy)
                    comboBox.setObjectName("{}ComboBox".format(key))  # change this
                    comboBox.move(120 + (i - i_offset) * offset1, 179 + j * offset2)
                    dwc_terms = list(set(selection_dict[key]).intersection(set(taxon_selections)))
                    if len(dwc_terms) > 0 and label.objectName() in dwc_terms:
                        selection_dict[key].remove(label.objectName())
                        comboBox.addItems(dwc_terms + sorted(selection_dict[key]))
                    else:
                        comboBox.addItems(sorted(selection_dict[key]))
                    comboBox.show()

                    if i in [2, 5, 8, 11]:
                        j += 1
                        i_offset += 3

        else:

            # otherwise, throw an error to show user they need to provide a file
            self.show_warning_messagebox("You need to provide a file to choose columns.")

    """
    /***************************************************************************
     galah-python query functions
     ***************************************************************************/

    /***************************************************************************
     * all of these functions will get input data from the UI.                 *
     *                                                                         *
     *   check_ala_backbone:                                                   *
     *       So far, this function runs the `search_taxa` function in `galah-  *
     *       python` to get back a list of taxon in the backbone that matches  *
     *       what the user gave as input.                                      * 
     *   prepare_query:                                                        *
     *       So far, this function gets the following information from the UI  *
     *       and places it in the appropriate place for the query:             *
     *             - email                                                     *
     *             - reason                                                    *
     *             - data_profile                                              *
     *             - taxonomy                                                  *
     *             - filters                                                   *
     *             - doi                                                       *
     *             - data fields                                               *
     *   check_num_occurrences:                                                *
     *       Checks the number of records that will be returned by the users'  *
     *       query.                                                            *
     *   get_species_list_count_statuses (IN PROGRESS):                        *
     *       So far, this function will get a list of species with the counts  *
     *       and download the csv (this last part will hopefully work soon)    *
     *   download_occurrences (IN PROGRESS):                                   *
     *       So far, this will run a check on how many records the user wants  *
     *       to download; if it is more than 5mil, don't allow them to down-   *
     *       load the records.  After the query passes that check, download    *
     *       occurrence records and load them as a vector layer into QGIS      *  
     *                                                                         *
     ***************************************************************************/
    """

    def check_ala_backbone(self):

        # get the taxon information
        taxon_info = self.parse_taxonomy()

        # Check for the following:
        # 1. If the taxon_info is a string and is set to "Closed", finish the function here
        # 2. Otherwise, run search_taxa with our taxon info
        if taxon_info in ["Closed", "No columns"]:
            return None
        else:
            taxa_table = galah.search_taxa(
                taxa=taxon_info["taxa"],
                identifiers=taxon_info["identifiers"],
                scientific_name=taxon_info["scientific_name"],
                specific_epithet=taxon_info["specific_epithet"],
            )

        # calculating some statistics on matches
        total = taxa_table.shape[0]
        match_statistics = {
            "Exact Matches": taxa_table.loc[taxa_table["matchType"] == "exactMatch", "matchType"].count(),
            "Higher Matches": taxa_table.loc[taxa_table["matchType"] == "higherMatch", "matchType"].count(),
            "Canonical Matches": taxa_table.loc[taxa_table["matchType"] == "canonicalMatch", "matchType"].count(),
            "Fuzzy Matches": taxa_table.loc[taxa_table["matchType"] == "fuzzyMatch", "matchType"].count(),
            "Vernacular Matches": taxa_table.loc[taxa_table["matchType"] == "vernacularMatch", "matchType"].count(),
            "Taxon ID Matches": taxa_table.loc[taxa_table["matchType"] == "taxonIdMatch", "matchType"].count(),
            "Phrase Matches": taxa_table.loc[taxa_table["matchType"] == "phraseMatch", "matchType"].count(),
        }

        # initialise variables
        total_matches = 0
        stats_text = f"You have:\n\n"

        # loop over all statistics and add them to output if the number is greater than 0
        for key in match_statistics.keys():
            if match_statistics[key] > 0:
                stats_text += f"{key}: {match_statistics[key]}\n"
                total_matches += match_statistics[key]

        # see how many issues there are
        issues = total - total_matches

        # if there are issues, let the user know
        if issues > 0:

            # first, check for homonyms
            homonymns = taxa_table.loc[taxa_table["issues"] == "homonym", "issues"].count()
            other = total - total_matches - homonymns

            # add these stats to the overall text
            stats_text += f"\n\nIssues:\n\nHomonyms: {homonymns}\nOther: {other}"

        # show the statistics
        self.show_info_messagebox(text=str(stats_text))

        # Show the user the taxa table
        self.show_table_dialogbox(table=taxa_table, title="Results From Searching Taxonomic Backbone")

    def prepare_query(self, counts=False):

        # get information for the configuration options
        email = self.parse_email()  # email parsed correctly
        reason = self.parse_reason()  # reason parsed correctly
        data_profile = self.parse_data_profile()  # data profile parsed correctly
        atlas=self.atlasNames[self.atlasesComboBox.currentText()]

        # check to see if the user is using the data profile
        use_data_profile = False
        if data_profile not in [None, ""]:
            use_data_profile = True

        # check that email and reason are ticked; if not, throw error
        if not counts:

            # if no email is present, show user error message and exit
            if email in [None, ""]:
                self.show_warning_messagebox(
                    text="You need to provide an email to download occurrences", title="Warning"
                )
                return "provide_email"

            # if no reason is present, show user error message and exit
            if reason in [None, "", "-- All --"] and atlas not in ["Brazil","France","Guatemala","Portugal"]:
                self.show_warning_messagebox(
                    text="You need to provide a reason to download occurrences", title="Warning"
                )
                return "provide_reason"

        # set the configuration options here
        galah.galah_config(authenticate=False, email=email, reason=reason, data_profile=data_profile)

        # get any taxonomy argument
        taxonomy = self.parse_taxonomy()

        # get other parameters
        filters = self.parse_filters()

        # get the DOI, if any, from the DOI text box
        doi = self.parse_doi_as_query()

        # add any spatial queries
        spatial = self.parse_spatial()

        # check for authoritative lists
        auth_lists = False
        EPBC = False

        # get the data resource IDs of authoritative lists
        auth_drs = (
            list(threatenedLists.values())
            + list(sensitiveLists.values())
            + list(migratoryLists.values())
            + list(nonNativeLists.values())
        )
        EPBC_value = threatenedLists["EPBC"]

        # check if any lists are part of the filter; if so, set EPBC and auth_lists to True, depending
        # on what values are set in the GUI
        if filters is not None:
            if any("species_list_uid" in f for f in filters):
                list_filters = [f for f in filters if "species_list_uid" in f]
                for lf in list_filters:
                    if EPBC_value in lf:
                        EPBC = True
                    if any(ad in lf for ad in auth_drs):
                        auth_lists = True

        # set fields
        fields = self.set_data_fields()

        # return taxonomy, filters and fields
        return taxonomy, filters, spatial, doi, fields, use_data_profile

    def check_num_occurrences(self):

        # get all potential filters
        taxonomy, filters, spatial, doi, fields, use_data_profile = self.prepare_query(counts=True)

        # draw bounding boxes around shapes, as a lot of shapes are too complicated to
        # pass in current iteration of galah
        bboxes_for_querying = self.draw_bounding_box(shapes=spatial)

        # check for invalid number of shapes warning
        if bboxes_for_querying == "Invalid number of shapes":
            return None

        # if there are multiple shapefiles, loop over all shapes
        if isinstance(bboxes_for_querying, list) and len(bboxes_for_querying) > 0:

            # initialise the total number of counts
            total_counts = 0

            # loop over all bounding boxes to get approximate total number of counts
            for bbox in bboxes_for_querying:
                counts = galah.atlas_counts(
                    taxa=taxonomy["taxa"],
                    identifiers=taxonomy["identifiers"],
                    scientific_name=taxonomy["scientific_name"],
                    specific_epithet=taxonomy["specific_epithet"],
                    filters=filters,
                    bbox=bbox,
                    use_data_profile=use_data_profile,
                )
                total_counts += counts["totalRecords"][0]

            # get approximate number of counts, as this currently draws bounding boxes instead
            # of using full shapes
            text = "Your query will return approximately {} records.".format(total_counts)

        else:

            # get the number of records their query will return
            counts = galah.atlas_counts(
                taxa=taxonomy["taxa"],
                identifiers=taxonomy["identifiers"],
                scientific_name=taxonomy["scientific_name"],
                specific_epithet=taxonomy["specific_epithet"],
                filters=filters,
                use_data_profile=use_data_profile,
            )

            # set the text for the message box
            text = "Your query will return {} records.".format(counts["totalRecords"][0])

        # show dialog box with number of counts
        self.show_info_messagebox(text=text, title="Number of records")

    def get_species_list_counts_statuses(self):

        # first, check for data layers
        self.show_layers_for_species_list()

        # return None if no layers are selected
        if self.speciesListLayers is None:
            return None

        # get layers on the canvas
        layers = iface.mapCanvas().layers()

        # layers to compile
        layers_to_compile = []

        # loop over all layers to only select the specified data layers
        for l in layers:
            if l.name() in self.speciesListLayers:
                layers_to_compile.append(l)

        
        # keys should be the same for all data layers
        keys = list(layers_to_compile[0].getFeatures())[0].attributeMap().keys()
        
        # get total number of features
        total_features = 0
        for l in layers:
            total_features += l.featureCount()

        overall_dict = {key: [None for x in range(total_features)] for key in keys}
        df = pd.DataFrame(overall_dict)
        offset = 0

        for l in layers_to_compile:

            features = list(l.getFeatures())
            
            for f in features:
                attrs = f.attributeMap()
                for a in attrs.keys():
                    df.loc[offset,a] = attrs[a]
                offset += 1
       
        # TODO: 1. Potentially reorder columns
        # TODO: 2. Sum up all occurrences and counts
        # self.show_info_messagebox(text=f"{df.head()}")
        # df = pd.DataFrame()
        # for f in features:
        #     df = pd.concat([df,pd.DataFrame(f.attributeMap(),index=[0])])
        
        # self.show_info_messagebox(text=f"{df.head()}")

        # download the species list
        # self.download_species_list(species_list=species_list)

    def download_occurrences(self):

        # check to see if user wants to mint the DOI
        mint_doi = self.mint_doi()

        # get all possible filters for the query
        taxonomy, filters, spatial, doi, fields, use_data_profile = self.prepare_query(counts=False)

        # check to see if user provided email and reason
        if taxonomy in ["provide_email", "provide_reason"]:
            return None

        # make bounding boxes
        bboxes_for_querying = self.draw_bounding_box(shapes=spatial)

        # set up total counts in case there are multiple shapes
        total_counts = 0

        # if there are shapes, loop over them; otherwise, only get one query count
        if isinstance(bboxes_for_querying, list) and len(bboxes_for_querying) > 0:
            for bbox in bboxes_for_querying:
                # get number of records user will download
                counts = galah.atlas_counts(
                    taxa=taxonomy["taxa"],
                    identifiers=taxonomy["identifiers"],
                    scientific_name=taxonomy["scientific_name"],
                    specific_epithet=taxonomy["specific_epithet"],
                    filters=filters,
                    bbox=bbox,
                    use_data_profile=use_data_profile,
                    doi=doi,
                )
                total_counts += counts["totalRecords"][0]
        else:
            counts = galah.atlas_counts(
                taxa=taxonomy["taxa"],
                identifiers=taxonomy["identifiers"],
                scientific_name=taxonomy["scientific_name"],
                specific_epithet=taxonomy["specific_epithet"],
                filters=filters,
                use_data_profile=use_data_profile,
            )

        # check number of records the user will download; throw an error if there are
        # more than 5mil records to download
        if int(counts["totalRecords"][0]) > 5000000 or total_counts > 505000:

            # set the text for the message box
            text = "You cannot download more than 5 million records at a time.  You have tried to download {} records.  Please filter your query further.".format(
                counts["totalRecords"][0]
            )

            # show dialog box with number of counts
            self.show_info_messagebox(text=text, title="Number of records")

            # exit query
            return None

        # initialise the latitude and longitude (will change depending on different atlases)
        atlas = self.atlasNames[self.atlasesComboBox.currentText()]
        latitude = latitude_dict[atlas]
        longitude = longitude_dict[atlas]

        # if there are shapes, loop over them; otherwise, only get one query count
        if isinstance(bboxes_for_querying, list) and len(bboxes_for_querying) > 0:

            # initialise an all_occurrences dataframe for concatenating
            all_occurrences = pd.DataFrame()

            # loop over all bounding boxes
            for i, bbox in enumerate(bboxes_for_querying):

                # get occurrences for an individual bounding box
                if mint_doi:
                    doi, occurrences = galah.atlas_occurrences(
                        taxa=taxonomy["taxa"],
                        identifiers=taxonomy["identifiers"],
                        scientific_name=taxonomy["scientific_name"],
                        specific_epithet=taxonomy["specific_epithet"],
                        filters=filters,
                        mint_doi=mint_doi,
                        fields=fields,
                        bbox=bbox,
                        use_data_profile=use_data_profile,
                        print_doi=False,
                    )

                    # test this
                    self.show_doi_messagebox(doi=doi, title="Your DOI")

                else:
                    occurrences = galah.atlas_occurrences(
                        taxa=taxonomy["taxa"],
                        identifiers=taxonomy["identifiers"],
                        scientific_name=taxonomy["scientific_name"],
                        specific_epithet=taxonomy["specific_epithet"],
                        filters=filters,
                        mint_doi=mint_doi,
                        fields=fields,
                        bbox=bbox,
                        use_data_profile=use_data_profile,
                    )

                # turn the occurrences into geodataframe
                gdf_occ = gpd.GeoDataFrame(
                    occurrences, geometry=gpd.points_from_xy(occurrences[longitude], occurrences[latitude], crs=4326)
                )

                # get all points within the shape
                within = gdf_occ[gdf_occ.within(spatial[i].as_shapely())]

                # concatenate all the occurrences together
                all_occurrences = pd.concat([all_occurrences, within], ignore_index=True)

        else:

            # get the occurrence records (add other fields too)
            if mint_doi:

                # mint a doi
                doi, occurrences = galah.atlas_occurrences(  # doi, occurrences
                    taxa=taxonomy["taxa"],
                    identifiers=taxonomy["identifiers"],
                    scientific_name=taxonomy["scientific_name"],
                    specific_epithet=taxonomy["specific_epithet"],
                    filters=filters,
                    mint_doi=mint_doi,
                    fields=fields,
                    doi=doi,
                    use_data_profile=use_data_profile,
                    print_doi=False,
                )

                # test this
                self.show_doi_messagebox(doi=doi, title="Your DOI")

            else:
                occurrences = galah.atlas_occurrences(
                    taxa=taxonomy["taxa"],
                    identifiers=taxonomy["identifiers"],
                    scientific_name=taxonomy["scientific_name"],
                    specific_epithet=taxonomy["specific_epithet"],
                    filters=filters,
                    mint_doi=mint_doi,
                    fields=fields,
                    doi=doi,
                    use_data_profile=use_data_profile,
                )

            # turn the occurrences into geodataframe
            all_occurrences = gpd.GeoDataFrame(
                occurrences, geometry=gpd.points_from_xy(occurrences[longitude], occurrences[latitude], crs=4326)
            )

        # initialise layer
        layer = QgsVectorLayer("Point?crs=EPSG:4326", "data", "memory")
        provider = layer.dataProvider()

        # create the attributes list from the column names (as these are the attributes)
        attributes_list = list(all_occurrences.columns)

        # Now, add fields that you will be getting from the data frame user has downloaded
        # (attributes_dict is decliared in vocab.py)
        for a in attributes_list:
            if a == "geometry":
                continue
            elif a not in attributes_dict.keys():
                self.show_warning_messagebox(
                    text="{} is not found in the attributes dictionary.\n\n{}".format(a, attributes_dict)
                )
                return None
            provider.addAttributes([QgsField(a, attributes_dict[a])])
        layer.updateFields()

        # loop over all occurrences
        for i, row in all_occurrences.iterrows():
            f = QgsFeature()
            point = QgsPointXY(row[longitude], row[latitude])
            f.setGeometry(QgsGeometry.fromPointXY(point))
            temp_attr = [row[x] for x in attributes_list]
            f.setAttributes(temp_attr)
            provider.addFeature(f)

        # update the layer after all points have been added to it
        layer.updateExtents()

        # Add the layer to the project
        QgsProject.instance().addMapLayer(layer)
