import os

import galah
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import QMessageBox,QDialog
from datetime import datetime

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), "alaQgisPlugin_dialog_base.ui"))

# Set default combo box
COMBOBOX_ALL_LABEL = "-- All --"


class AlaQgisPluginDialog(QtWidgets.QDialog, FORM_CLASS):
    """
    /***************************************************************************
     AlaQgisPluginDialog
                                     A QGIS plugin
     This plugin is designed to get ALA data into QGIS
     Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                                 -------------------
             begin                : 2025-10-01
             git sha              : $Format:%H$
             copyright            : (C) 2025 by Atlas of Living Australia
             email                : amanda.buyan@csiro.au
     ***************************************************************************/

    /***************************************************************************
     *                                                                         *
     *   This program is free software; you can redistribute it and/or modify  *
     *   it under the terms of the GNU General Public License as published by  *
     *   the Free Software Foundation; either version 2 of the License, or     *
     *   (at your option) any later version.                                   *
     *                                                                         *
     ***************************************************************************/
    """

    def __init__(self, parent=None):
        """
        Initialise the plugin
        """
        super(AlaQgisPluginDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # populate predefined values
        self._populate_reasons()
        self._populate_data_profiles()

        # # test this
        # self.startDateEdit.setDate(datetime(1752,9,14))
        # self.endDateEdit.setDate(datetime(1752,9,14))

        # define the actions clicking on these buttons will run
        self.checkAlaBackbonePushButton.clicked.connect(self.check_ala_backbone) 
        self.checkNumOccurrences.clicked.connect(self.check_num_occurrences)
        self.occDownload.clicked.connect(self.download_occurrences)
        self.speciesListCountsStatuses.clicked.connect(self.get_species_list_counts_statuses)
        self.uploadSpeciesListPushButton.clicked.connect(self.upload_species_list)

    """
    /***************************************************************************
     Variable Declaration
     ***************************************************************************/

    /***************************************************************************
     * Predefined values for the plugin, either statically or dynamically      *
     * defined.                                                                *
     *                                                                         *
     * Static Dictionaries:                                                    *
     *                                                                         *
     *   basisOfRecord                                                         *
     *       Describes how observations are made                               *
     *   threatenedLists                                                       *
     *       Authoritative lists of threatened species available in the ALA    *
     *   sensitiveLists                                                        *
     *       Authoritative lists of sensitive species available in the ALA     *
     *   migratoryLists                                                        *
     *       Authoritative lists of migratory species available in the ALA     *
     *   nonNativeLists                                                        *
     *       Authoritative lists of non-Native species available in the ALA    *
     *                                                                         *
     * Dynamic Dictionaries:                                                   *
     *                                                                         *
     *   dataProfiles                                                          *
     *       List of existing data profiles to filter your query  in the ALA   *
     *   reasons                                                               *
     *       List of all reasons for downloading data in the ALA               *
     *                                                                         *
     ***************************************************************************/
    """

    """
    /*****************
     Combo box values
     *****************/
    """
    # get ALA profiles
    profiles = galah.show_all(profiles=True)

    # initialise data profiles dict
    dataProfiles = {
        COMBOBOX_ALL_LABEL: None,
    }

    # add data profile values to dict
    for i,row in profiles.iterrows():
        dataProfiles[row["name"]] = row["shortName"]

    # get reasons in ALA
    rs = galah.show_all(reasons=True)

    # initialise reasons dict
    reasons = {
        COMBOBOX_ALL_LABEL: None,
    }

    # add reasons to dict
    for i,row in rs.iterrows():
        reasons[row["name"]] = row["id"]

    """
    /*****************
     Tick box values
     *****************/
    """
    threatenedLists = {
        "ACT": "dr649",
        "EPBC": "dr656",
        "NSW": "dr650",
        "NT": "dr651",
        "QLD": "dr652",
        "SA": "dr653",
        "TAS": "dr654",
        "VIC": "dr655",
        "WA": "dr2201",
    }

    sensitiveLists = {
        "ACT": "dr2627",
        "NSW": "dr487",
        "NT": "dr492",
        "QLD": "dr493",
        "SA": "dr884",
        "TAS": "dr491",
        "VIC": "dr490",
        "WA": "dr467",
    }

    migratoryLists = {
        "Bonn": "dr18987",
        "CAMBA": "dr18989",
        "JAMBA": "dr18988",
        "ROKAMBA": "dr18990",
    }

    nonNativeLists = {"NonNative All": "dr32213"}

    """
    /***************************************************************************
     Populating predefined values
     ***************************************************************************/

    /***************************************************************************
     * all of these functions will populate predefined values, which are       *
     * defined above.                                                          *
     *                                                                         *
     *   _populate_data_profiles:                                              *
     *       set default combo box values from variable `dataProfiles`         *
     *   _populate_reasons:                                                    *
     *       set default combo box values from variable `reasons`              *
     *                                                                         *
     ***************************************************************************/
    """

    def _populate_data_profiles(self):
        vals = list(self.dataProfiles.keys())
        self.dataProfileComboBox.addItems(sorted(vals))

    def _populate_reasons(self):
        vals = list(self.reasons.keys())
        self.reasonsComboBox.addItems(sorted(vals))

    """
    /***************************************************************************
     Showing information to the user
     ***************************************************************************/

    /***************************************************************************
     * all of these functions will show information to the user, be it         *
     * information, warning or display a data table.                           *
     *                                                                         *
     *   show_info_messagebox:                                                 *
     *       gives the user information, for example the number of records     *
     *       they will download with their current query                       *
     *   show_warning_messagebox:                                              *
     *       gives the user a warning, for example if they are missing their   *
     *       email address                                                     *
     *   show_table_dialogbox:                                                 *
     *       shows the user a table of their data, such as the taxonomy they   *
     *       will be using to query their chosen atlas                         *
     *                                                                         *
     ***************************************************************************/
    """
    
    def show_info_messagebox(self,text=None,title=None):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Icon.Information)
        msg.setText(text)
        msg.setWindowTitle(title)
        msg.setStandardButtons(QMessageBox.StandardButton.Ok | QMessageBox.StandardButton.Cancel)
        retval = msg.exec()


    def show_warning_messagebox(self,title=None,text=None):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Icon.Warning)
        msg.setText(text)
        msg.setWindowTitle(title)
        msg.setStandardButtons(QMessageBox.StandardButton.Ok | QMessageBox.StandardButton.Cancel)
        retval = msg.exec()


    def show_table_dialogbox(self,table=None,title=None):
        """
        /* Work in progress */
        """
        # create the window and set the title
        msg = QDialog()
        msg.setWindowTitle(title)
        
        # initialise the table widget
        msg.tableWidget = QtWidgets.QTableWidget(msg)
        
        # try this
        msg.tableWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        msg.tableWidget.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)

        # get the number of rows and columns
        nb_row = table.shape[0]
        nb_col = table.shape[1]

        # set the number of rows and columns
        msg.tableWidget.setRowCount(nb_row)
        msg.tableWidget.setColumnCount(nb_col)

        # add the data to the table
        for row in range (nb_row):
            for col in range(nb_col):
                item = QtWidgets.QTableWidgetItem(str(table.iloc[row,col])) # was [row]
                msg.tableWidget.setItem(row,col,item)

        # add column names
        msg.tableWidget.setHorizontalHeaderLabels([u'{}'.format(x) for x in table.columns]) #list(table.columns)) #[u'Column1',u'Column2'])
        
        # resize table so user can see the table
        msg.tableWidget.resizeRowsToContents()
        msg.tableWidget.resizeColumnsToContents()

        # resize the dialog box to accommodate the table
        dialogWidth = msg.tableWidget.horizontalHeader().length() + 24
        dialogHeight= msg.tableWidget.verticalHeader().length() + 24
        msg.setFixedSize(dialogWidth, dialogHeight)

        # msg.setStandardButtons(QDialog.StandardButton.Ok | QDialog.StandardButton.Cancel)
        retval = msg.exec()

    """
    /***************************************************************************
     Functions for getting data from the UI
     ***************************************************************************/

    /***************************************************************************
     * all of these functions will parse input data from the UI.               *
     *                                                                         *
     *   mint_doi:                                                             *
     *       get a DOI for your query so you can easily retrieve it            *
     *   parse_authoritative_lists:                                            *
     *       get IDs of all authoritative lists user has chosen                *
     *   parse_basis_of_record:                                                *
     *       user chooses between observations and specimens; assign Darwin    *
     *       Core terms accordingly.                                           *
     *   parse_data_profile:                                                   *
     *       get variable user has chosen in data profile combo box            *
     *   parse_date:                                                           *
     *       get start date and end date values from the date tab              *
     *   parse_doi_as_query:                                                   *
     *       if someone has provided a DOI, use it as your query argument      *
     *   parse_email:                                                          *
     *       gets user email for adding to query                               *
     *   parse_present_absent:                                                 *
     *       determine if users want absence, presence, or both                *
     *   parse_reason:                                                         *
     *       get variable user has chosen in data profile combo box            *
     *   parse_taxonomy:                                                       *
     *       **to write**                                                      *
     *   set_data_fields:                                                      *
     *       tells galah-python what fields to download from Python.  Checks   *
     *       whether or not user has an authoritative list in their filters    *
     *       and add statuses if so.                                           *
     *                                                                         *
     ***************************************************************************/
    """

    def mint_doi(self):
        """
        /* Check to see if it is working */
        """
        if self.createDoiCheckBox.isChecked():
            return True

    # check completed
    def parse_authoritative_lists(self):
        
        # initialise lists variable
        lists = []

        # Threatened Lists
        if self.actThreatCheckBox.isChecked():
            lists.append(self.threatenedLists["ACT"])
        if self.epbcThreatCheckBox.isChecked():
            lists.append(self.threatenedLists["EPBC"])
        if self.nswThreatCheckBox.isChecked():
            lists.append(self.threatenedLists["NSW"])
        if self.ntThreatCheckBox.isChecked():
            lists.append(self.threatenedLists["NT"])
        if self.qldThreatCheckBox.isChecked():
            lists.append(self.threatenedLists["QLD"])
        if self.saThreatCheckBox.isChecked():
            lists.append(self.threatenedLists["SA"])
        if self.tasThreatCheckBox.isChecked():
            lists.append(self.threatenedLists["TAS"])
        if self.vicThreatCheckBox.isChecked():
            lists.append(self.threatenedLists["VIC"])
        if self.waThreatCheckBox.isChecked():
            lists.append(self.threatenedLists["WA"])

        # Sensitive Lists
        if self.actSensCheckBox.isChecked():
            lists.append(self.sensitiveLists["ACT"])
        if self.nswSensCheckBox.isChecked():
            lists.append(self.sensitiveLists["NSW"])
        if self.ntSensCheckBox.isChecked():
            lists.append(self.sensitiveLists["NT"])
        if self.qldSensCheckBox.isChecked():
            lists.append(self.sensitiveLists["QLD"])
        if self.saSensCheckBox.isChecked():
            lists.append(self.sensitiveLists["SA"])
        if self.tasSensCheckBox.isChecked():
            lists.append(self.sensitiveLists["TAS"])
        if self.vicSensCheckBox.isChecked():
            lists.append(self.sensitiveLists["VIC"])
        if self.waSensCheckBox.isChecked():
            lists.append(self.sensitiveLists["WA"])

        # Migratory Lists
        if self.bonnMigratoryCheckBox.isChecked():
            lists.append(self.migratoryLists["Bonn"])
        if self.cambaCheckBox.isChecked():
            lists.append(self.migratoryLists["CAMBA"])
        if self.jambaCheckBox.isChecked():
            lists.append(self.migratoryLists["JAMBA"])
        if self.rokambaCheckBox.isChecked():
            lists.append(self.migratoryLists["ROKAMBA"])

        # Non-Native Lists
        if self.nonNativeCheckBox.isChecked():
            lists.append(self.nonNativeLists["NonNative All"])

        # create appropriate filters for this and return as string
        if len(lists) > 0:
            return "species_list_uid={}".format(",".join(lists))
        else:
            return None

    # check completed
    def parse_basis_of_record(self):

        # declare observations vs. specimens values
        basisOfRecord_observation = [
            "HUMAN_OBSERVATION",
            "MACHINE_OBSERVATION",
            "OBSERVATION",
            "OCCURRENCE",
        ]
        basisOfRecord_specimen = [
            "FOSSIL_SPECIMEN",
            "MATERIAL_CITATION",
            "MATERIAL_SAMPLE",
            "LIVING_SPECIMEN",
            "PRESERVED_SPECIMEN",
        ]

        # declare list of potential values
        bor = []

        # check to see if any/all boxes are check
        if self.specimensCheckBox.isChecked():
            bor += basisOfRecord_specimen
        if self.observationsCheckBox.isChecked():
            bor += basisOfRecord_observation

        # create appropriate filters for this and return as string
        if len(bor) > 0:
            return "basisOfRecord={}".format(",".join(bor))
        else:
            return None

    # check completed
    def parse_data_profile(self):
        for p in self.dataProfiles:
            if self.dataProfileComboBox.currentText() == p:
                return self.dataProfiles[p]

    # check completed
    def parse_date(self):
        # get the dates and convert them to datetime
        startDate = self.startDateCalendarWidget.selectedDate()
        endDate = self.endDateCalendarWidget.selectedDate()
        d,m,y = startDate.getDate()

        # first, check for default values
        if startDate == endDate:
            if startDate == datetime.now().date():
                return None,None
            d,m,y = startDate.getDate()
            return 'eventDate={}'.format(datetime(d,m,y).isoformat()),None

        # then, check if someone either swapped the dates or put the wrong ones in
        elif startDate > endDate:
            self.show_warning_messagebox(text="Your start date is further in the future than your end date.")
            # throw error here?

        # otherwise, we have a valid datetime window
        else:
            if endDate == datetime.now().date():
                d,m,y = startDate.getDate()
                return 'eventDate>={}Z'.format(datetime(d,m,y).isoformat()),None
            else:
                d1,m1,y1 = startDate.getDate()
                d2,m2,y2 = endDate.getDate()
                startDateString = 'eventDate>={}Z'.format(datetime(d1,m1,y1).isoformat())
                endDateString = 'eventDate=<{}Z'.format(datetime(d2,m2,y2).isoformat())
                return startDateString,endDateString
        
        # return None as the deafult
        return None,None

    def parse_doi_as_query(self):
        """
        /* Check to see if it is working */
        """
        doi = self.doiLineEdit.text()
        if doi not in [None,'']:
            return doi
        return None

    # check completed
    def parse_email(self):
        return self.emailLineEdit.text()

    # check completed
    def parse_present_absent(self):

        # initialise status list
        status = []

        # check if present/absent boxes are ticked
        if self.absentCheckBox.isChecked():
            status.append("ABSENT")
        if self.presentCheckBox.isChecked():
            status.append("PRESENT")

        # create appropriate filters for this and return as string
        if len(status) > 0:
            return "occurrenceStatus={}".format(",".join(status))
        else:
            return None

    # check completed
    def parse_reason(self):
        for r in self.reasons:
            if self.reasonsComboBox.currentText() == r:
                return self.reasons[r]

    def parse_taxonomy(self):
        """
        /* Check to see if it is working */
        """
        if self.speciesLineEdit.text() not in [None,'']:
            return self.speciesLineEdit.text().split(',')
        return None
            
    def set_data_fields(self,auth_lists=False,EPBC=False):
        """
        /* Check to see if it is working */
        """
        fields = ["basic","dataProviderName","dataResourceName"]
        if auth_lists:
            fields += ["stateConservation"]
        if EPBC:
            fields += ["countryConservation"]
        return fields

    """
    /***************************************************************************
     Query Data
     ***************************************************************************/

    /***************************************************************************
     * all of these functions will get input data from the UI.                 *
     *                                                                         *
     *   parse_filters:                                                        *
     *       parse the filters from the UI and format them for galah-python    *
     *                                                                         *
     ***************************************************************************/
    """

    # check completed
    def parse_filters(self):

        # initialise filters list
        filters = []

        # get all types of filters from the UI
        authoritative_lists = self.parse_authoritative_lists()
        date1,date2 = self.parse_date()
        bor = self.parse_basis_of_record()
        pa = self.parse_present_absent()

        # loop over all filters to see which ones are present
        for fs in [authoritative_lists,bor,pa,date1,date2]:
            if fs is not None:
                filters.append(fs)

        # if there are no filters, return None
        if len(filters) == 0:
            return None
        
        # return whatever filters were present in the UI
        return filters

    """
    /***************************************************************************
     Button actions (not galah-python functions)
     ***************************************************************************/

    /***************************************************************************
     * all of these functions will get input data from the UI.                 *
     *                                                                         *
     *   upload_species_list:                                                  *
     *       set default combo box values from variable `dataProfiles`         *
     *                                                                         *
     ***************************************************************************/
    """

    def upload_species_list(self):
        """
        TODO: test that this works
        """
        dialog = QtWidgets.QFileDialog()
        dialog.setFileMode(QtWidgets.QFileDialog.AnyFile)
        dialog.setFilter(QtWidgets.QDir.Files)

        if dialog.exec_():
            file_name = dialog.selectedFiles()

            if file_name[0].endswith(".csv"):
                with open(file_name[0], "r") as f:
                    data = f.read()
                    self.textEditor.setPlainText(data)
                    f.close()
            else:
                pass

    """
    /***************************************************************************
     galah-python query functions
     ***************************************************************************/

    /***************************************************************************
     * all of these functions will get input data from the UI.                 *
     *                                                                         *
     *   check_ala_backbone:                                                   *
     *       X        *
     *   prepare_query:                                             *
     *       X    *
     *   check_num_occurrences:                                          *
     *       X      *
     *   get_species_list_count_statuses:                                                    *
     *       X              *
     *   download_occurrences: *
     *       X*
     *                                                                         *
     ***************************************************************************/
    """

    def check_ala_backbone(self):
        """
        /* Check to see if it is working */
        """
        taxonomy_list = self.parse_taxonomy()
        taxa_table = galah.search_taxa(taxa=taxonomy_list)
        self.show_table_dialogbox(table=taxa_table,title="testing") 

    def prepare_query(self,counts=False):

        # get information for the configuration options
        email = self.parse_email() # email parsed correctly
        reason = self.parse_reason() # reason parsed correctly
        data_profile = self.parse_data_profile() # data profile parsed correctly
        
        # check that email and reason are ticked; if not, throw error
        if not counts:

            # TODO: enable button ONLY IF both are present OR popup
            if email is None:
                self.show_warning_messagebox(text="You need to provide an email to download occurrences",title="Warning")
                return None

            if reason is None:
                self.show_warning_messagebox(text="You need to provide a reason to download occurrences",title="Warning")
                return None

        # set the configuration options here
        galah.galah_config(authenticate=False, email=email, reason=reason, data_profile=data_profile)

        # get any taxonomy argument
        taxonomy = self.parse_taxonomy()

        # get other parameters
        filters = self.parse_filters()
        self.show_info_messagebox(text=str(filters))
        
        # check for authoritative lists
        auth_lists=False
        EPBC=False

        # get the data resource IDs of authoritative lists
        auth_drs = list(self.threatenedLists.values()) + list(self.sensitiveLists.values()) + list(self.migratoryLists.values()) + list(self.nonNativeLists.values()) 
        EPBC_value = self.threatenedLists['EPBC']

        # check if any lists are part of the filter; if so, set EPBC and auth_lists to True, depending 
        # on what values are set in the GUI
        if filters is not None:
            if any("species_list_uid" in f for f in filters):
                list_filters = [f for f in filters if "species_list_uid" in f]
                for lf in list_filters:
                    if EPBC_value in lf:
                        EPBC=True
                    if any(ad in lf for ad in auth_drs):
                        auth_lists=True

        # set fields
        fields = self.set_data_fields(auth_lists=auth_lists,EPBC=EPBC)

        # return taxonomy, filters and fields
        return taxonomy,filters,fields

    def check_num_occurrences(self):

        # get all potential filters
        taxonomy,filters,fields = self.prepare_query(counts=True)

        # get the number of records their query will return
        counts = galah.atlas_counts(taxa=taxonomy,filters=filters)

        text = "Your query will return {} records.".format(counts["totalRecords"][0])

        # show dialog box with number of counts
        self.show_info_messagebox(text=text,title="Number of counts")

    def get_species_list_counts_statuses(self):

        # check to see if user wants to mint the DOI
        mint_doi = self.mint_doi()

        # get all possible filters for the query
        taxonomy,filters,fields = self.prepare_query()

        # get the species list with counts and statuses (test this)
        species_list = galah.atlas_species(
            taxa=taxonomy,
            filters=filters,
            mint_doi=mint_doi,
            fields=fields,
        )

        # TODO: add a way to get the csv into QGIS

    def download_occurrences(self):

        # check to see if user wants to mint the DOI
        mint_doi = self.mint_doi()

        # get all possible filters for the query
        taxonomy,filters,fields = self.prepare_query()

        # get the occurrence records (add other fields too)
        occurrences = galah.atlas_occurrences(
            taxa=taxonomy,
            filters=filters,
            mint_doi=mint_doi,
            fields=fields,
        )

        # TODO: add a way to get the csv into QGIS
